### ISSUE TITLE
Nor working anymore

### ISSUE THREAD

**Issue by tnfno** [liangqi/nrkopptak#1]
Looks like NRK has changed something a few weeks ago, it does not work anymore.  Error seems to be that the manifest cannot be found.

**Comment by infoman61** [comment]
I tried to download "Elvis - Gjennombruddet" fra nrk.no (TV) now, and 
that works OK.

**Comment by KnutHelland** [comment]
This is probably related.

I had problems with downloading as well, but after some debugging I managed to find this error message:

```
Can't verify SSL peers without knowing which Certificate Authorities to trust

This problem can be fixed by either setting the PERL_LWP_SSL_CA_FILE
envirionment variable or by installing the Mozilla::CA module.

To disable verification of SSL peers set the PERL_LWP_SSL_VERIFY_HOSTNAME
envirionment variable to 0.  If you do this you can't be sure that you
communicate with the expected peer.
```

and it works again if I call it like:

```
PERL_LWP_SSL_VERIFY_HOSTNAME=0 nrk-opptak ...
```

on windows that would be

```
SET PERL_LWP_SSL_VERIFY_HOSTNAME=0
nrk-opptak ...
```
